#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-threejs
Version  : 0.3.4
Release  : 52
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/threejs_0.3.4.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/threejs_0.3.4.tar.gz
Summary  : Interactive 3D Scatter Plots, Networks and Globes
Group    : Development/Tools
License  : MIT
Requires: R-base64enc
Requires: R-crosstalk
Requires: R-htmlwidgets
Requires: R-igraph
BuildRequires : R-base64enc
BuildRequires : R-crosstalk
BuildRequires : R-htmlwidgets
BuildRequires : R-igraph
BuildRequires : R-shiny
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Three.js and R
Three.js widgets for R and shiny. The package includes
* graphjs: an interactive network visualization widget
* scatterplot3js: a 3-d scatterplot widget similar to, but more limited than, the scatterplot3d function
* globejs: a somewhat silly widget that plots data and images on a 3-d globe

%prep
%setup -q -n threejs
pushd ..
cp -a threejs buildavx2
popd
pushd ..
cp -a threejs buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745275303

%install
export SOURCE_DATE_EPOCH=1745275303
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/threejs/DESCRIPTION
/usr/lib64/R/library/threejs/INDEX
/usr/lib64/R/library/threejs/LICENSE
/usr/lib64/R/library/threejs/Meta/Rd.rds
/usr/lib64/R/library/threejs/Meta/data.rds
/usr/lib64/R/library/threejs/Meta/demo.rds
/usr/lib64/R/library/threejs/Meta/features.rds
/usr/lib64/R/library/threejs/Meta/hsearch.rds
/usr/lib64/R/library/threejs/Meta/links.rds
/usr/lib64/R/library/threejs/Meta/nsInfo.rds
/usr/lib64/R/library/threejs/Meta/package.rds
/usr/lib64/R/library/threejs/NAMESPACE
/usr/lib64/R/library/threejs/R/threejs
/usr/lib64/R/library/threejs/R/threejs.rdb
/usr/lib64/R/library/threejs/R/threejs.rdx
/usr/lib64/R/library/threejs/data/LeMis.RData
/usr/lib64/R/library/threejs/data/ego.RData
/usr/lib64/R/library/threejs/demo/click_animation.R
/usr/lib64/R/library/threejs/demo/click_animation2.R
/usr/lib64/R/library/threejs/demo/crosstalk.R
/usr/lib64/R/library/threejs/examples/globe/server.R
/usr/lib64/R/library/threejs/examples/globe/ui.R
/usr/lib64/R/library/threejs/examples/graph/server.R
/usr/lib64/R/library/threejs/examples/graph/ui.R
/usr/lib64/R/library/threejs/examples/scatterplot/server.R
/usr/lib64/R/library/threejs/examples/scatterplot/ui.R
/usr/lib64/R/library/threejs/help/AnIndex
/usr/lib64/R/library/threejs/help/aliases.rds
/usr/lib64/R/library/threejs/help/paths.rds
/usr/lib64/R/library/threejs/help/threejs.rdb
/usr/lib64/R/library/threejs/help/threejs.rdx
/usr/lib64/R/library/threejs/html/00Index.html
/usr/lib64/R/library/threejs/html/R.css
/usr/lib64/R/library/threejs/htmlwidgets/globe.js
/usr/lib64/R/library/threejs/htmlwidgets/globe.yaml
/usr/lib64/R/library/threejs/htmlwidgets/lib/jquery/jquery.min.js
/usr/lib64/R/library/threejs/htmlwidgets/lib/threejs-111/CanvasRenderer.js
/usr/lib64/R/library/threejs/htmlwidgets/lib/threejs-111/Detector.js
/usr/lib64/R/library/threejs/htmlwidgets/lib/threejs-111/Projector.js
/usr/lib64/R/library/threejs/htmlwidgets/lib/threejs-111/StateOrbitControls.js
/usr/lib64/R/library/threejs/htmlwidgets/lib/threejs-111/TrackballControls.js
/usr/lib64/R/library/threejs/htmlwidgets/lib/threejs-111/three.min.js
/usr/lib64/R/library/threejs/htmlwidgets/scatterplotThree.js
/usr/lib64/R/library/threejs/htmlwidgets/scatterplotThree.yaml
/usr/lib64/R/library/threejs/images/circle.png
/usr/lib64/R/library/threejs/images/disc.png
/usr/lib64/R/library/threejs/images/moon.jpg
/usr/lib64/R/library/threejs/images/plus.png
/usr/lib64/R/library/threejs/images/world.jpg
/usr/lib64/R/library/threejs/tests/threejs.R
